# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screen1.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(582, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_2.addWidget(self.checkBox)
        self.Set_time_interval = QtWidgets.QPushButton(self.layoutWidget)
        self.Set_time_interval.setObjectName("Set_time_interval")
        self.horizontalLayout_2.addWidget(self.Set_time_interval)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 3)
        self.Refresh = QtWidgets.QPushButton(self.layoutWidget)
        self.Refresh.setObjectName("Refresh")
        self.gridLayout.addWidget(self.Refresh, 2, 0, 1, 1)
        self.Check_time = QtWidgets.QLabel(self.layoutWidget)
        self.Check_time.setText("")
        self.Check_time.setObjectName("Check_time")
        self.gridLayout.addWidget(self.Check_time, 1, 0, 1, 3)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 4, 0, 1, 3)
        self.Check_all = QtWidgets.QPushButton(self.layoutWidget)
        self.Check_all.setObjectName("Check_all")
        self.gridLayout.addWidget(self.Check_all, 2, 1, 1, 1)
        self.Delete = QtWidgets.QPushButton(self.layoutWidget)
        self.Delete.setEnabled(False)
        self.Delete.setObjectName("Delete")
        self.gridLayout.addWidget(self.Delete, 2, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 3)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Url = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Url.setObjectName("Url")
        self.gridLayout_2.addWidget(self.Url, 0, 1, 1, 2)
        self.Add = QtWidgets.QPushButton(self.layoutWidget1)
        self.Add.setEnabled(False)
        self.Add.setObjectName("Add")
        self.gridLayout_2.addWidget(self.Add, 1, 1, 1, 1)
        self.Duplicate = QtWidgets.QPushButton(self.layoutWidget1)
        self.Duplicate.setObjectName("Duplicate")
        self.gridLayout_2.addWidget(self.Duplicate, 3, 1, 1, 1)
        self.Url_status = QtWidgets.QLabel(self.layoutWidget1)
        self.Url_status.setText("")
        self.Url_status.setWordWrap(True)
        self.Url_status.setObjectName("Url_status")
        self.gridLayout_2.addWidget(self.Url_status, 2, 1, 1, 2)
        self.Clear = QtWidgets.QPushButton(self.layoutWidget1)
        self.Clear.setObjectName("Clear")
        self.gridLayout_2.addWidget(self.Clear, 3, 2, 1, 1)
        self.Check = QtWidgets.QPushButton(self.layoutWidget1)
        self.Check.setEnabled(False)
        self.Check.setObjectName("Check")
        self.gridLayout_2.addWidget(self.Check, 1, 2, 1, 1)
        self.Log = QtWidgets.QTextEdit(self.layoutWidget1)
        self.Log.setObjectName("Log")
        self.gridLayout_2.addWidget(self.Log, 4, 1, 1, 2)
        self.gridLayout_3.addWidget(self.splitter, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 582, 23))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout_Author = QtWidgets.QAction(MainWindow)
        self.actionAbout_Author.setObjectName("actionAbout_Author")
        self.actionCommon_problems = QtWidgets.QAction(MainWindow)
        self.actionCommon_problems.setObjectName("actionCommon_problems")
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionAbout_Author)
        self.menuHelp.addAction(self.actionHelp)
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Websites Monitor"))
        self.checkBox.setText(_translate("MainWindow", "Atuto check (5 min)"))
        self.Set_time_interval.setText(_translate("MainWindow", "Set time interval"))
        self.Refresh.setText(_translate("MainWindow", "Refresh"))
        self.listWidget.setToolTip(_translate("MainWindow", "Websites list"))
        self.Check_all.setText(_translate("MainWindow", "Check all"))
        self.Delete.setText(_translate("MainWindow", "Delete"))
        self.Url.setToolTip(_translate("MainWindow", "Input url"))
        self.Add.setText(_translate("MainWindow", "Add"))
        self.Duplicate.setText(_translate("MainWindow", "Copy"))
        self.Clear.setText(_translate("MainWindow", "Clear"))
        self.Check.setText(_translate("MainWindow", "Check"))
        self.Log.setToolTip(_translate("MainWindow", "Log"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About Websites Monitor"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout_Author.setText(_translate("MainWindow", "About Author"))
        self.actionCommon_problems.setText(_translate("MainWindow", "Common problems"))
